name: PWA CI/CD Workflow

on:
  push:
    branches:
      - master
      - errors
      - utilidades
  pull_request:
    branches:
      - master
      - errors
      - utilidades
  workflow_dispatch: 

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4.2.1

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar Dependencias
        run: npm install

      - name: Configurar Caché
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

  build:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4.2.1

      - name: Compilar Proyecto
        run: npm run build

      - name: Subir Artefacto
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ../dist

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4.2.1

      - name: Ejecutar Pruebas Unitarias
        run: npm test

      - name: Ejecutar Pruebas E2E
        run: npm run cypress

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    if: github.ref == 'refs/heads/master'  # Solo se despliega si es la rama master

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4.2.1

      - name: Desplegar a Firebase
        uses: FirebaseHosting/deploy-action@v0
        with:
          project_id: your_project_id

  errors-notify:
    runs-on: ubuntu-latest
    needs: [test]

    if: github.ref == 'refs/heads/errors'  # Notificación solo para la rama errors

    steps:
      - name: Notificar Errores
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
          payload: |
            {
              "text": "Hubo un error en las pruebas en la rama errors.",
              "channel": "#ci-notifications"
            }

  utilidades-notify:
    runs-on: ubuntu-latest
    needs: [test]

    if: github.ref == 'refs/heads/utilidades'  # Notificación solo para la rama utilidades

    steps:
      - name: Notificar Utilidades
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
          payload: |
            {
              "text": "La rama utilidades ha pasado las pruebas correctamente.",
              "channel": "#ci-notifications"
            }
