name: PWA CI/CD Workflow LABARBADA

on:
  push:
    branches:
      - master
      - errors
      - utilidades
  pull_request:
    branches:
      - master
      - errors
      - utilidades
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configurar Caché
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Instalar Dependencias
        run: npm install

      - name: Compilar Proyecto
        run: npm run build

      - name: Verificar Archivos de Compilación
        run: ls -la ./dist  # Listar el contenido de la carpeta dist para verificar

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Descargar Artefactos de Compilación
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

      - name: Verificar Archivos Descargados
        run: ls -la ./dist  # Verificar que los archivos se descargaron correctamente

      - name: Desplegar a Vercel
        working-directory: ./dist
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN
