name: Flujo de trabajo de CI/CD de la BARBADA

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Construir la aplicación
        run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Construir la aplicación
        run: npm run build

      - name: Desplegar a producción en Hostinger vía FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/

      - name: Notificar despliegue exitoso
        if: success()  # Solo se ejecuta si el despliegue fue exitoso
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.eventName === 'pull_request') {
              github.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: ✅ Despliegue automático en Hostinger vía FTP completado exitosamente para el commit ${github.sha}.
              });
            } else {
              console.log("Despliegue exitoso :)");
            }