name: PWA CI/CD Workflow LABARBADA

on:
  push:
    branches:
      - master
      - errors
      - utilidades
  pull_request:
    branches:
      - master
      - errors
      - utilidades
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configurar Caché
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Instalar Dependencias
        run: npm install

      - name: Compilar Proyecto
        run: npm run build

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.node-version }}
          path: ./dist
